### ISSUE TITLE
现在这些地方

### ISSUE THREAD

**Issue by jayceftg** [ilovexjp/health-code-index#1]
要白名单什么的，那些不行哇？

**Comment by ilovexjp** [comment]
请描述清楚问题

**Comment by jamiekinmanchg23** [comment]
1.天府健康通场所码时间显示能否和健康码一样实时更新。2，建议点击省内核酸查看后和跳形程卡场所码一样跳转一个核酸详情页面用户可以自定义核酸时间，3，健康码页面核酸点击更新那儿能不能换成倒计时秒数动态，要求有点多，楼主好人，下辈子美利坚，不胜感谢
