### ISSUE TITLE
希望天府健康通 健康码中加入证明已打疫苗的“金框” 十分感谢

### ISSUE THREAD

**Issue by 118253070146** [ilovexjp/health-code-index#140]
- [ ] 我已经仔细阅读过 README 中的全部内容。
- [ ] 这是一个对**现有项目**的错误反馈或改进建议，不是应该在 Discussions 提出的问题或新项目提议。

**Comment by ilovexjp** [comment]
不知道你说的是不是名字旁边金色的“接种完成”标志？之前有 Issue 提出这个已经删掉了，我当时没有多加确认。如果这个“接种完成”标志还在的话我会把它加回来；如果是换了样式的话我会去再看一下。

**Comment by wangzuxian1314** [comment]
> 不知道你说的是不是名字旁边金色的“接种完成”标志？之前有 Issue 提出这个已经删掉了，我当时没有多加确认。如果这个“接种完成”标志还在的话我会把它加回来；如果是换了样式的话我会去再看一下。

你的皮炎子真紧啊

**Comment by wangzuxian1314** [comment]
> 不知道你说的是不是名字旁边金色的“接种完成”标志？之前有 Issue 提出这个已经删掉了，我当时没有多加确认。如果这个“接种完成”标志还在的话我会把它加回来；如果是换了样式的话我会去再看一下。

真想糙fan你

**Comment by nannan119** [comment]
这个问题是错误的，天府健康通没有任何已接种疫苗标志

**Comment by 118253070146** [comment]
> 这个问题是错误的，天府健康通没有任何已接种疫苗标志

sorry 我记得以前有 思维固化了就以为一直有 没想到取消了

**Comment by 118253070146** [comment]
> 不知道你说的是不是名字旁边金色的“接种完成”标志？之前有 Issue 提出这个已经删掉了，我当时没有多加确认。如果这个“接种完成”标志还在的话我会把它加回来；如果是换了样式的话我会去再看一下。

**Comment by 118253070146** [comment]
> 不知道你说的是不是名字旁边金色的“接种完成”标志？之前有 Issue 提出这个已经删掉了，我当时没有多加确认。如果这个“接种完成”标志还在的话我会把它加回来；如果是换了样式的话我会去再看一下。

sorry 我记得以前有 思维固化了就以为一直有 没想到取消了
