### ISSUE TITLE
防疫那么难，不懂开源这个项目的意义在哪里？明知非法还要为之。

### ISSUE THREAD

**Issue by luneice** [ilovexjp/health-code-index#205]
防疫那么难，不懂开源这个项目的意义在哪里？明知非法还要为之。

_Originally posted by @luneice in https://github.com/ilovexjp/health-code-index/discussions/198_

**Comment by ilovexjp** [comment]
请前往 https://github.com/ilovexjp/health-code-index/discussions/198 进行讨论
