### ISSUE TITLE
希望增加黄码/红码模式

### ISSUE THREAD

**Issue by water1st** [ilovexjp/health-code-index#226]
发表 Issue 前，请先确认

- 已经仔细阅读过 README 中的全部内容。
- 这是一个对**现有项目**的错误反馈或改进建议。问题和新项目提议请在 Discussions 讨论。
- 没有打开的相同 Issue。
- 在 Issue 中明确存在问题的具体子项目。

在确认后，你可以在发表 Issue 时删除此模板中的内容。
希望增加绿黄红码自由切换的功能

**Comment by xhsmile** [comment]
加红黄马的意义何在？

**Comment by xiwinnie8964** [comment]
那不就助纣为虐了？

**Comment by water1st** [comment]
可以借此居家办公
