### ISSUE TITLE
豫康码的release中缺失icon

### ISSUE THREAD

**Issue by fxxkhnjkm** [ilovexjp/health-code-index#263]
![Screenshot_2022-11-11-15-17-51-047_com android chrome](https://user-images.githubusercontent.com/117954350/201287190-0bba29a2-773d-4acf-b967-64f2eb9fcd86.jpg)
这是我自己部署后的效果 查看了一下release中没有icon的图标 谢谢大佬

**Comment by ilovexjp** [comment]
我看了一下，`henan-hc/static` 里面的文件是全的，请你再检查一下是不是没有配置好。

**Comment by fxxkhnjkm** [comment]
<img width="256" alt="image" src="https://user-images.githubusercontent.com/117954350/201297179-aaa4f2bb-b682-4e4a-bc66-cf1dc8bde6f9.png">
一共就只有这些吗大佬 麻烦你了 我第一次搞这个不太懂

**Comment by ilovexjp** [comment]
> <img alt="image" width="256" src="https://user-images.githubusercontent.com/117954350/201297179-aaa4f2bb-b682-4e4a-bc66-cf1dc8bde6f9.png">
> 一共就只有这些吗大佬 麻烦你了 我第一次搞这个不太懂

还有一些 A* 开头的图片文件

**Comment by fxxkhnjkm** [comment]
> 

在release里没有看见耶

**Comment by ilovexjp** [comment]
> > 
> 
> 在release里没有看见耶

这些文件没有后缀名，还请再仔细检查一下。

**Comment by fxxkhnjkm** [comment]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/117954350/201310721-ada024e0-1cea-4d74-bb9e-8479b7a19219.png">
这是我下载下来的包 还是没有找到欸 是不是需要特定的软件才能看见😭

**Comment by fxxkhnjkm** [comment]
我换了一个解压软件 看到啦！！谢谢大佬 我是啥b

**Comment by xiwinnie8964** [comment]
我直接部署好像也没有，但是用服务器是有的，可能Windows缺少一些依赖？
还有别用迅雷，那玩意会卖了你的。

**Comment by ilovexjp** [comment]
> 这是因为图片的文件名里有*星号，而Windows系统不允许文件名里带星号，所以解压后会被改名或消失。只能先上传到Linux服务器再解压。

之前没注意到，我改一下这个名字
