### ISSUE TITLE
粤康码主页名字第一个字星号的建议

### ISSUE THREAD

**Issue by RickyUKI** [ilovexjp/health-code-index#272]
如果手动修改名字主页顶上的名字会显示全名，与粤康码显示名字第一个为星号不符，如手动改星号则核酸名字也会显示为星号。

![E4AFC3F5-3409-43FA-B85F-2481DD646FE5](https://user-images.githubusercontent.com/7813582/201408273-a57f6d5c-0160-4cd3-bdf5-eb311ad91380.jpeg)
![111CAA1B-991B-4C77-A2B4-9FF9182C0C89](https://user-images.githubusercontent.com/7813582/201408278-199e1239-536c-47d0-80a6-55d9995908c1.jpeg)

**Comment by ilovexjp** [comment]
感谢反馈，之后会更新这点。

**Comment by RickyUKI** [comment]
感谢大佬更新！

**Comment by RickyUKI** [comment]
感谢大佬更新！
