### ISSUE TITLE
北京健康宝标题位置需要修改请留意！

### ISSUE THREAD

**Issue by sutrachant** [ilovexjp/health-code-index#273]
模拟器的扫码结果很完美了！但自查询的页面打开后，最上面的标题位置应该是靠左显示“北京健康宝”，目前模拟器标题却是中间显示“健康宝”，请修正！截图是官方自查询请参考！
![IMG_20221112_120733](https://user-images.githubusercontent.com/118004894/201456401-bb7e92f5-5ad0-482e-a956-90494d95b8d0.jpg)

**Comment by ilovexjp** [comment]
本项目根据 iOS 微信小程序样式制作，其中标题是居中的。
