### ISSUE TITLE
自己部署源码的话，任意一个地区的码打开行程码，都是跳转为404，如果从目录进入行程码又正常。演示的地址没这个问题

### ISSUE THREAD

**Issue by aibertmark** [ilovexjp/health-code-index#277]
发表 Issue 前，请先确认

- 已经仔细阅读过 README 中的全部内容。
- 这是一个对**现有项目**的错误反馈或改进建议。问题和新项目提议请在 Discussions 讨论。
- 没有打开的相同 Issue。
- 在 Issue 中明确存在问题的具体子项目。

在确认后，你可以在发表 Issue 时删除此模板中的内容。
自己部署源码的话，任意一个地区的码打开行程码，都是跳转为404，如果从目录进入行程码又正常。演示的地址没这个问题

**Comment by ilovexjp** [comment]
是否将健康码模拟放在域名根目录？如果没放在根目录，可以去修改一下 `base.js` 中的 `navigateHome` 和 `navigateToTripCard` 的跳转地址。

**Comment by HAMAN23333** [comment]
> 是否将健康码模拟放在域名根目录？如果没放在根目录，可以去修改一下 `base.js` 中的 `navigateHome` 和 `navigateToTripCard` 的跳转地址。

分别在`navigateHome` 和 `navigateToTripCard`的两个跳转地址尾端里添加`index .html`即可，我自己是用Vercel部署的

**Comment by lianfengcom** [comment]
> > 是否将健康码去简单地寻找某个地址`base.js`根`navigateHome`目录？`navigateToTripCard`
> 
> 分别在`navigateHome`和`navigateToTripCard`两个跳转地址的末尾添加里`index.html`约的，我自己是用 Vercel 部署的

改为这样的吗：navigateHome(){window.location.href="/index.html"}function navigateToTripCard(){window.location.href="/trip-card/index.html"}我改了，似乎还是不行，不知道哪错了？请指教。

**Comment by oplle** [comment]
自己部署千万不要放根目录，自建过tls梯子的都知道，防火墙会对你访问的ip或网址进行探测，很容易就能发现你的首页内容。

**Comment by aibertmark** [comment]
> 自己千万不要知道，自建过部署梯子的都放或者你发起访问的网址，很容易找到目录的首页内容。
就是没有放在根目录，所以提示404出错，自己改的似乎不正确。
