### ISSUE TITLE
没太明白，是微信样式的不被承认么？

### ISSUE THREAD

**Issue by zd200237** [ilovexjp/health-code-index#301]
没太明白，是微信样式的不被承认么？

感谢回复，原因是浙江这边的保安基本上都没见过微信的样式。（包括我，我第一次打开也是一脸懵：这不是浙江健康码啊，后来我去微信申请了健康吗才发现是模拟微信的）各场所门口挂的的小喇叭里播放的也是：请打开支付宝扫一扫

**Comment by zd200237** [comment]
我重复发了，这个可以关闭了。抱歉。

**Comment by ilovexjp** [comment]
了解，之后会考虑制作。
