### ISSUE TITLE
浙江健康码已经过时

### ISSUE THREAD

**Issue by robben16** [ilovexjp/health-code-index#344]
![Screenshot_2022-11-14-09-36-56-368_com eg android AlipayGphone-edit](https://user-images.githubusercontent.com/8064420/201557685-882bc523-79c3-44da-b2a4-8c68552a41be.jpg)

最新的样式如图，另外建议加入浙江场所码

**Comment by ilovexjp** [comment]
这个是杭州健康码，项目发布时特别说明过“不包含杭州健康码”。
