### ISSUE TITLE
求广西健康码、龙江健康码、湖北场所码。这些是大家比较急用的，希望下一批开发。辛苦了@ilovexjp (还有目前各码的支付宝版本）

### ISSUE THREAD

**Issue by Swimmingclub33066** [ilovexjp/health-code-index#367]
求广西健康码、龙江健康码、湖北场所码。这些是大家比较急用的，希望下一批开发。辛苦了@ilovexjp (还有目前各码的支付宝版本）

**Comment by ilovexjp** [comment]
麻烦不要再开 Issue 了，新项目请发在讨论区，模板和 README 上面都有注明。上一个已经帮你转过去了。
