### ISSUE TITLE
中国有很多边缘省份诸如广西、蒙古、黑龙江、吉林，甚至西藏新疆等，这些地区并不发达，绝大多数人包括那里的大学生在内，会翻墙的、甚至会用电子邮件的、知道如何在issue里提出需求的人，都非常少。这就造成这些人群中即使有会发声的，也是极少数。然而很明显他们代表着的是他们背后千千万万不会发声的邻居和亲人。他们同样在遭受过度防疫的危害。我想，我们应该有人替他们发声。我们有义务帮助这些边缘贫困地区的人。 在其他帖子里，我观察到有这些地区的人已经提出了请求，比如@389895972 ,@xxooomg, @Kifranei 等。然而并没有人回复他们的贴文。希望我们能够帮助他们。@ilovexjp 你对大家的付出，大家一定非常感谢！

### ISSUE THREAD

**Issue by ghost** [ilovexjp/health-code-index#370]
中国有很多边缘省份诸如广西、蒙古、黑龙江、吉林等，这些地区并不发达，绝大多数人包括那里的大学生在内，会翻墙的、甚至会用电子邮件的、知道如何在issue里提出需求的人，都非常少。这就造成这些人群中即使有会发声的，也是极少数。然而很明显他们代表着的是他们背后千千万万不会发声的邻居和亲人。他们同样在遭受过度防疫的危害。我想，我们应该有人替他们发声。我们有义务帮助这些边缘贫困地区的人。 在其他帖子里，我观察到有这些地区的人已经提出了请求，比如@389895972 ,@xxooomg, @Kifranei 等。然而并没有人回复他们的贴文。希望我们能够帮助他们。@ilovexjp 你对大家的付出，大家一定非常感谢！

**Comment by ilovexjp** [comment]
重複發表 https://github.com/ilovexjp/health-code-index/discussions/369
