### ISSUE TITLE
iOS 无法打开，显示"safari can't establish a secure connection "

### ISSUE THREAD

**Issue by thatsBlinc** [ilovexjp/health-code-index#39]
- [ ] 我已经仔细阅读过 README 中的全部内容。
- [ ] 这是一个对**现有项目**的错误反馈或改进建议，不是应该在 Discussions 提出的问题或新项目提议。
怎么解决的呢?

**Comment by ilovexjp** [comment]
网页演示仅供参考，可根据源码自行部署。
