### ISSUE TITLE
ios13以下机型无法正常显示base.js内容

### ISSUE THREAD

**Issue by xzfdsf21** [ilovexjp/health-code-index#50]
ios13以下机型无法正常显示base.js内容，请问是不是有高级语法不支持？

**Comment by ilovexjp** [comment]
可能是 [Optional Chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)，这个在 Safari 13.1 才开始支持。

**Comment by xzfdsf21** [comment]
感谢回复！研究了很久
function addStorageField(id, selector, name, placeholder) {
    var elements = document.querySelector(selector);
    
    elements.innerText = placeholder;
}
但是，精简成这样一个脚本js都不能运行，其他浏览器和高级版ios可以加载，对了，我的版本是ios13.3

**Comment by xzfdsf21** [comment]
见笑了，用傻瓜方法确定说selector语法不支持

**Comment by ilovexjp** [comment]
> 见笑了，用傻瓜方法确定说selector语法不支持

`querySelector` 方法应该是支持的，我之后应该会把 Optional Chaining 改掉以兼容更多浏览器。当然最好的话还是升级一下浏览器版本（在 iOS 就是升级系统版本），不然很多网站的加载可能都会有问题。

**Comment by xzfdsf21** [comment]
感谢回复，querySelector支持，但function addStorageField2(selector, placeholder)  那个selector变量写到html具体的位置中就能调用js。停留到Ios13说因为一直越狱，升级了最新系统就失去了很多东西。

**Comment by ilovexjp** [comment]
> 感谢回复，querySelector支持，但function addStorageField2(selector, placeholder) 那个selector变量写到html具体的位置中就能调用js。停留到Ios13说因为一直越狱，升级了最新系统就失去了很多东西。

之前的更新应该已经修复了这个问题。我把所有的 Optional Chaining 改掉了。

**Comment by xzfdsf21** [comment]
感谢大佬修复，测试完美适配，能让更多人用了
