### ISSUE TITLE
能支持黄码吗

### ISSUE THREAD

**Issue by chasel-hu** [ilovexjp/health-code-index#51]
- [ ] I have read all the README carefully.
- [ ] This is a bug report or feature request about an **existing** project, rather than a general question or new project proposal that should be raised in Discussions.

**Comment by xzfdsf21** [comment]
自己上传一个黄码图片就可以了，PNG转base64

**Comment by ilovexjp** [comment]
参见 https://github.com/ilovexjp/ykm-simulator/issues/11
