### ISSUE TITLE
【反馈完毕】

### ISSUE THREAD

**Issue by di7gan** [ilovexjp/health-code-index#63]
作者已经收到，所以删除信息了！

**Comment by di7gan** [comment]
强调一下：电信有一个程序叫防疫平台，只能你的姓名和手机似乎就能查到你的健康码等情况，建议在这个程序增加这种提示。
我所知道的是学校有这种防疫平台，你变码了他们是知道的。

**Comment by ilovexjp** [comment]
- 关于未完成接种疫苗的提示，目前没想到应用的场景。
- 制作健康码其它颜色不符合本项目初衷，之后也不会制作这类请求。参见 https://github.com/ilovexjp/ykm-simulator/issues/11 。

**Comment by ilovexjp** [comment]
至于“代码只有一行”的问题，这是由于保护开发人员身份等原因对源代码做了压缩处理，如果希望编辑的话可以使用美化工具展开后进行修改，和源代码差距不会很大。之后可能会考虑在不受限的地方发布源码。

**Comment by di7gan** [comment]
谢谢！
