### ISSUE TITLE
建议做成PWA 就解决 网址需要科学的问题了

### ISSUE THREAD

**Issue by jamninetyfive** [ilovexjp/health-code-index#90]
- [ ] 我已经仔细阅读过 README 中的全部内容。
- [ ] 这是一个对**现有项目**的错误反馈或改进建议，不是应该在 Discussions 提出的问题或新项目提议。

**Comment by zengjw33** [comment]
如果网址不需要科学,会不会造成滥用.
这个项目估计很快就黄了

**Comment by jamninetyfive** [comment]
> 目前已经是PWA了，非常完美，但是我部署的环境是非80端口就存在问题，不知道是不是因为js的跨源问题

看看sw 不用代理 我这里基本打不开

**Comment by wangzuxian1314** [comment]
我想糙你族宗十玖代！

**Comment by jamninetyfive** [comment]
> 我想糙你族宗十玖代！

github都来撒野..

**Comment by wangzuxian1314** [comment]
> 

糙fan你

**Comment by wangzuxian1314** [comment]
> > 我想糙你族宗十玖代！
> 
> github都来撒野..

你的皮炎子不错！加点仑化油舒服

**Comment by wangzuxian1314** [comment]
> > 我想糙你族宗十玖代！
> 
> github都来撒野..

糙思你

**Comment by jamninetyfive** [comment]
> > > 我想糙你族宗十玖代！
> > 
> > 
> > github都来撒野..
> 
> 糙思你

机器人？

**Comment by wangzuxian1314** [comment]
> > 我想糙你族宗十玖代！
> 
> github都来撒野..

糙你流水水

**Comment by ilovexjp** [comment]
目前已经支持 PWA，但并没有支持离线的功能，计划之后会支持。

**Comment by jamninetyfive** [comment]
> 目前已经支持 PWA，但并没有支持离线的功能，计划之后会支持。


嗯嗯离线很关键，还有关一下 双击缩放，编辑框点取消不要重置默认值。
